openapi: "3.0.0"
info:
  version: 1.0.0
  title: Management API
servers:
  - url: http://localhost:8080/management
paths:
  /members:
    get:
      summary: Get all the members
      operationId: GetMembers
      tags:
        - member
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MemberDto"
        '500':
          description: Something bad happened
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    MemberDto:
      type: object
      required:
        - firstName
        - lastName
        - gender
        - isActive
        - nationality
        - position
        - phoneNumber
        - emailAddress
        - homeAddress
        - remarks
      properties:
        firstName: 
          type: string
        lastName:
          type: string
        gender:
          type: string  
        isActive:
          type: boolean
        nationality:
          type: string  
        title:
          type: string
        phoneNumber:
          type: string
        emailAddress:
          type: string
        homeAddress:
          type: string
        remarks: 
          type: string        

    Error:            # Can be referenced as '#/components/schemas/Error'
      type: object
      properties:
        code:
          type: integer
        message:
          type: string          